---
title: "Research"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{css, echo = FALSE}
d-article p {
  text-align: justify;
}
```


# Working Papers

### [Do Low-stakes Visits to Schools Affect Student Performance?: Evidence From a Large-scale Monitoring System in Peru](https://drive.google.com/file/d/1P2Z99_xIK192Ud7Jm2FR-p9BXFtdEl4U){target="_blank"} (Job Market Paper)

Findings from prior studies of the effects of low-stakes monitoring (monitoring unaccompanied by explicit incentives or punishments) on student achievement in developing countries are mixed. Because most of these initiatives were carried out on a small scale by non-governmental organizations, these findings may lack validity in the case of large-scale government interventions. I investigate the educational impact of the Semaforo Escuela program. This is a large-scale monitoring system in Peru that implements unannounced monthly school inspections, the results of which are reported to local education officials. To analyze the causal effect of these monitoring visits, I use the random variation in the selection of visited schools in the program’s first year to estimate causal effects of low-stakes monitoring on student math and reading scores. Although I fail to find evidence that a monitoring visit enhances school-level student performance on average, there is a positive effect of monitoring on reading test scores at low-performing urban schools and when urban schools are visited in the months preceding the exam date. 

### Girls Outperforming Boys: Pre-school Gender Gap in Literacy and Numeracy Skills in African Countries (With Julie Buhl-Wiggers, Rebecca Thornton, and Mahounan Yedomiffi)

Little is known about whether there exists a gender gap in pre-school measures of early numeracy and literacy skills, and what predictors – if any – help to understand any difference across gender. We use two rounds of available Demographic and Health Surveys (DHS) and Multiple Indicator Cluster Survey (MICS), collected from 2011 to 2019 across 25 African countries, and compare mothers’ reports of numbers and letters identification among boys and girls ages 3–4. We report that, on average, girls are 2 percentage points more likely to identify at least ten letters of the alphabet, 1 percentage point more likely to read four words, and 2 percentage points more likely to identify the first ten numbers. These magnitudes are small in absolute terms but relevant given the low rates of these competences in African countries (on average 20 percent). We find that part of this gender gap is due to girls accessing early childhood education programs. In addition, we report that both mother's and father's literacy show a positive intergenerational effect on their children's outcomes. The mother's literacy has a greater magnitude than the father's and is more relevant for their daughter's competencies.

# Work in Progress


### Effects of Political Corruption on Political Attitudes: Evidence from theOdebrecht Scandal in Peru

Does political corruption erode people’s attitudes towards political institutions and democracy? I test this hypothesis in the context of Peru by exploiting a corruption shock, the Odebrecht case, which revealed the corruption of high-ranked politicians in the tenders for large infrastructure projects. I draw on household survey data collected during the unanticipated Odebrecht scandal, which allows me to adopt a quasi-experimental approach. I find that, following revelations of corruption by governmental officials, people’s confidence in different political institutions and democracy does not vary significantly. These findings are in line with no change in perceived corruption as one of the main problems of the country after the scandal.

# Publications

### [Assets and Economic Context – Factors related to poverty in Peru](https://www.bcrp.gob.pe/en/publications/working-papers/wp-2013-13-assets-and-economic-context-factors-related-to-the-poverty-in-peru.html){target="_blank"}  (in Spanish, translated tittle)
Central Reserve Bank of Peru. Working Paper Series Nº 2013-013. November, 2013.

### [Focalización de los programas sociales en el Perú: 2007 – 2011](https://www.bcrp.gob.pe/docs/Publicaciones/Revista-Moneda/moneda-155/moneda-155-03.pdf){target="_blank"} (in Spanish, translated tittle)
Revista Moneda, issue 155, p. 18-22. 2013}

### [Depth of outreach in the context of microfinance commercialization in Peru](https://revistas.pucp.edu.pe/index.php/economia/article/view/2686){target="_blank"} (in Spanish, translated tittle)
Revista Economía. Departamento de Economía – Pontificia Universidad Católica del Perú. Vol. XXXIV, N° 68, pp. 33-63. December, 2011




